=== rsansan079/Actv-UD4_LdM/Actv2/Mejora/Mejora.dtd
<!ELEMENT fruteria (fruta+)>
<!ELEMENT fruta (codigo, tipo , color , arbol , proveniencia , clasificacion , cultivo)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT arbol (#PCDATA)>
<!ELEMENT proveniencia (#PCDATA)>
<!ELEMENT clasificacion (#PCDATA)>
<!ELEMENT cultivo (#PCDATA)>

=== rsansan079/Actv-UD4_LdM/Actv3/Mejora/Mejora_D.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE fruteria SYSTEM "Mejora.dtd">
    <fruteria>
    <fruta>
      <codigo>001</codigo>
      <tipo>Acida</tipo>
      <color>Naranja</color>
      <arbol>Naranjo</arbol>
      <proveniencia>Asia</proveniencia>
      <clasificacion>Sapindales</clasificacion>
      <cultivo>citrico</cultivo>
    </fruta>
    
    <fruta>
        <codigo>002</codigo>
        <tipo>Dulce</tipo>
        <color>Roja/Verde</color>
        <arbol>Manzano</arbol>
        <proveniencia>Asia</proveniencia>
        <clasificacion>Malus </clasificacion>
        <cultivo>pom√°cea</cultivo>
      </fruta>
    </fruteria>
