=== rsansan079/Actv-UD4_LdM/Actv7/Editorial/Editorial.dtd
<!ELEMENT informe (fecha, regiones)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT regiones (region+)>
<!ELEMENT region (nombre, trimestre+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT trimestre (librosVendidos)>
<!ATTLIST trimestre numero CDATA #REQUIRED>
<!ELEMENT librosVendidos (#PCDATA)>

=== rsansan079/Actv-UD4_LdM/Actv7/Editorial/Editorial.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE informe SYSTEM "Editorial.dtd">

<informe>
    <fecha>2024-02-01</fecha>
        <regiones>
            <region>
                <nombre>Norte</nombre>
                <trimestre numero='1'>
                    <librosVendidos>24000</librosVendidos>
                </trimestre>
                <trimestre numero='2'>
                    <librosVendidos>38600</librosVendidos>
                </trimestre>
                <trimestre numero='3'>
                    <librosVendidos>NO_INFO</librosVendidos>
                </trimestre>
                <trimestre numero='4'>
                    <librosVendidos>NO_INFO</librosVendidos>
                </trimestre>
            </region>
            <region>
                <nombre>Centro</nombre>
                <trimestre numero='1'>
                    <librosVendidos>NO_INFO</librosVendidos>
                </trimestre>
                <trimestre numero='2'>
                    <librosVendidos>16080</librosVendidos>
                </trimestre>
                <trimestre numero='3'>
                    <librosVendidos>25000</librosVendidos>
                </trimestre>
                <trimestre numero='4'>
                    <librosVendidos>29000</librosVendidos>
                </trimestre>
            </region>
            <region>
                <nombre>sur</nombre>
                <trimestre numero='1'>
                    <librosVendidos>27000</librosVendidos>
                </trimestre>
                <trimestre numero='2'>
                    <librosVendidos>31400</librosVendidos>
                </trimestre>
                <trimestre numero='3'>
                    <librosVendidos>40100</librosVendidos>
                </trimestre>
                <trimestre numero='4'>
                    <librosVendidos>30000</librosVendidos>
                </trimestre>
            </region>
        </regiones>
</informe>
