=== rsansan079/Actv-UD4_LdM/Actv5/mejora/mejora.dtd
<!ELEMENT libros (libro+)>
<!ELEMENT libro (ISBN, Titulo, Autor, Editorial, Observaciones?, Precio)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT Titulo (#PCDATA)>
<!ELEMENT Autor (#PCDATA)>
<!ELEMENT Editorial (#PCDATA)>
<!ELEMENT Observaciones (#PCDATA)>
<!ELEMENT Precio (#PCDATA)>

=== rsansan079/Actv-UD4_LdM/Actv5/mejora/mejora_d.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libros SYSTEM "mejora.dtd">
<libros>
    <libro>
        <ISBN>978-3-16-148410-0</ISBN>
        <Titulo>El Señor de los Anillos</Titulo>
        <Autor>J.R.R. Tolkien</Autor>
        <Editorial>Minotauro</Editorial>
        <Observaciones>Edición especial con ilustraciones.</Observaciones>
        <Precio>25.99</Precio>
    </libro>
    <libro>
        <ISBN>978-0-385-00855-2</ISBN>
        <Titulo>Cien Años de Soledad</Titulo>
        <Autor>Gabriel García Márquez</Autor>
        <Editorial>Critica</Editorial>
        <Precio>19.95</Precio>
    </libro>
</libros>
